INSERT INTO ReadyLessons (id, title, link) VALUES (1, 'Past Simple', 'google.com');
INSERT INTO ReadyLessons (id, title, link) VALUES (2, 'Present Simple', 'google.com');
INSERT INTO ReadyLessons (id, title, link) VALUES (3, 'Present Perfect', 'google.com');
INSERT INTO ReadyLessons (id, title, link) VALUES (4, 'Past Perfect', 'google.com');
INSERT INTO ReadyLessons (id, title, link) VALUES (5, 'Present Simple 2', 'google.com');
INSERT INTO ReadyLessons (id, title, link) VALUES (6, 'Present Simple 3', 'google.com');
INSERT INTO ReadyLessons (id, title, link) VALUES (7, 'Present Simple 3', 'vk.com');
INSERT INTO ReadyLessons (id, title, link) VALUES (8, 'Present Simple 4', 'vk.com');
INSERT INTO ReadyLessons (id, title, link) VALUES (9, 'Present Simple 5', 'yandex.ru');
INSERT INTO ReadyLessons (id, title, link) VALUES (10, 'Future Perfect', 'gmail.com');
INSERT INTO ReadyLessons (id, title, link) VALUES (11, 'PPPPPP', 'genius.com');
